### PR TITLE
Changed access of initModules() in Robot to private

### LINKED ISSUE #49: initModules() Called Multiple Times
initModules() is called in the constructor of robot but isn't private (and is called a second time in many op modes), this needs to be addressed and fixed. It's probably best that this is fixed and tested on the robot to ensure it doesn't break anything.

### LINKED ISSUE #59: initModules() Called Multiple Times
initModules() is called in the constructor of robot but isn't private (and is called a second time in many op modes), this needs to be addressed and fixed. It's probably best that this is fixed and tested on the robot to ensure it doesn't break anything.

### PR DESCRIPTION
**Pull request by e3l**
Resolves #59.

### CODE REVIEW

**Comment by e3l** [comment]
To be tested

**Comment by e3l** [comment]
it didnt break anything

**Review by chop0 — DISMISSED** [review]
lgtm

**Review by chop0 — APPROVED** [review]
lgtm

**Review by chop0 — APPROVED** [review]

**Pull request merged**
