### PR TITLE
Data dumping

### LINKED ISSUE #12: Implement Data Dumping
We need to track all states over and over in each module and dump it to a file when we stop op-mode.
This will be useful for debugging odometry now and path following in the future.

### PR DESCRIPTION
**Pull request by chop0**
Resolves #12

### CODE REVIEW

**Comment by chop0** [comment]
uh oh i based the branch off the wrong thing

**Comment by chop0** [comment]
@albertcai101 is circularodometry ready, or should i rebase?

**Comment by e3l** [comment]
@chop0 resolve conflicts?

**Comment by chop0** [comment]
@e3l kk

**Comment by chop0** [comment]
hm?

**Pull request closed without merging**
